[buildPlans.TechnikMono]
family = "Technik Mono"
spacing = "term"
inherits = "ss15"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.TechnikMono.variants.design]
zero = "tall-slashed"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifed"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "curly-serifless"
eight = "crossing"
nine = "closed-contour"
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-q = "crossing"
capital-w = "straight-vertical-sides-flat-top-serifless"
l = "flat-tailed"
w = "straight-vertical-sides-flat-top-serifless"
